### ISSUE TITLE
attach a DOI to release? 

### ISSUE THREAD

**Issue by laurensorensen** [amiaopensource/cable-bible#34]
Hi there maintainer(s), I would like to cite this project in academic research, and wondering if you'd be willing to attach a DOI to one of the releases.
There are two services that I've found that can do this, lmk if you need a hand:
http://mozillascience.github.io/code-research-object/
and Zenodo:
https://guides.github.com/activities/citable-code/

Thanks!

**Comment by EG-tech** [comment]
Hi Lauren! This seems a great idea and easy to implement. Looking at these options, I'm partial to zenodo since their own code is open source.

There are a couple quick tweaks I'd like to make so long as we're getting into proper citation (i.e. contributors listed in the README) - this will spur me to get those done, tag a new release, and attach a DOI!

**Comment by EG-tech** [comment]
![image](https://user-images.githubusercontent.com/17784531/36941906-e7e8a750-1f33-11e8-8d50-7e6a42ccdd4a.png)

:+1:

**Comment by retokromer** [comment]
@EG-tech You could put it into the main page, as made for the [Time-based media art resources](https://github.com/amiaopensource/time-based-media-art).
