### ISSUE TITLE
gender inclusive language on github pages site

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/cable-bible#53]
hi,
feel free to disregard, but I was recently asked about alternatives to "male/female" language when referring to cables, and while I knew this had been addressed in the cable bible, it took me a minute to realize that the gender inclusive note was added only to the README and not the website proper. any chance you'd be willing/interested in adding this? from my perspective, redundancy would be good here.
thanks!
ben

**Comment by EG-tech** [comment]
hey Ben!

short answer is you're totally right that redundancy makes sense and it would be simple enough to dupe the language into a block on the sidebar of the actual site

long answer/context would be that, IIRC correctly, my thought process was that the cork/bottle terminology only ever actually appears in the naming convention for example images; i.e. that it was important to include with contribution instructions but that neither cork/bottle (nor M/F) appears in any meaningful way in the text of the site itself if you are just using it for reference

but since you raise it, that thinking is wrong on three counts:
1. image filenames with the cork/bottle language are readily apparent on the live site if you open or save images directly, inspect source, etc etc
2. some of the image source attribution URLs probably have the M/F language in them
3. if the purpose of the Cable Bible is to give context and guidance in the wide world of cables, it behooves us (me) to say something about this on the site itself

I will edit when I get the chance!

**Comment by retokromer** [comment]
@EG-tech Could you make a new release? Then I will update the formula as well. Thank you!

**Comment by bturkus** [comment]
thank you ethan! this is fab!
